import { Inter } from 'next/font/google'
import './globals.css'
import Header from "@/app/components/Header";
import { ClerkProvider } from '@clerk/nextjs'
import { frFR } from "@clerk/localizations";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  manifest: "/manifest.json",
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <ClerkProvider localization={frFR}>
          <html lang="fr">
              <body className={inter.className}>
                <Header/>
                {children}
              </body>
          </html>
      </ClerkProvider>

  )
}
